services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: arancia-opensearch
    environment:
      - cluster.name=arancia-opensearch
      - node.name=arancia-opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - arancia-opensearch-data:/usr/share/opensearch/data

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arancia-dashboards
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"
    command: ["yarn", "start:docker"]

  storybook:
    image: node:18-bullseye
    container_name: arancia-storybook
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "6006:6006"
    command: ["bash", "-lc", "yarn storybook --no-open --ci"]

volumes:
  arancia-opensearch-data:


